In [1]:
import pandas as pd

# Load the train and test DataFrames
train_df = pd.read_pickle("data/train.pkl")
test_df = pd.read_pickle("data/test.pkl")

# Display the first few rows of the DataFrames
print("Train DataFrame:")
display(train_df.head())

print("Test DataFrame:")
display(test_df.head())

# Check correlations for numerical columns in the train DataFrame
print("\nCorrelation Matrix (Train DataFrame):")
train_corr = train_df.select_dtypes(include=['int64', 'float64']).corr()
display(train_corr)

# Check correlations for numerical columns in the test DataFrame
print("\nCorrelation Matrix (Test DataFrame):")
test_corr = test_df.select_dtypes(include=['int64', 'float64']).corr()
display(test_corr)

# Save the correlation matrices as CSV files (optional)
train_corr.to_csv("data/train_correlations.csv")
test_corr.to_csv("data/test_correlations.csv")

Train DataFrame:

,eid,p31,p34,p46_i0,p47_i0,p48_i0,p49_i0,p50_i0,p51_i0,p52,...,p30870_i0,p30880_i0,p30890_i0,p30897_i0,p30900_i0,p130894,p130895,birth_date,age_at_baseline,target
0,ID_1,Category_D,25,21.842481,0.273070,25.788324,89.306982,39.826116,21.864889,Category_A,...,66.626955,96.821467,76.055925,0.043840,68.044442,2008-04-21,Category_E,1965-04-15,59,1
1,ID_2,Category_B,33,78.360127,1.135750,44.142222,75.653100,83.771701,91.961506,Category_E,...,79.581666,81.403491,42.618508,0.771692,52.102297,2015-05-15,Category_E,1967-05-19,52,0
2,ID_3,Category_A,9,31.253445,0.075037,0.942622,51.298032,52.549592,82.403842,Category_D,...,61.203799,47.812377,78.975174,-0.411959,31.559509,2019-05-11,Category_C,1951-08-01,47,0
3,ID_4,Category_C,79,21.156981,0.543026,40.886846,93.378278,3.891030,76.442123,Category_D,...,50.618399,23.009571,7.182506,0.863609,69.471249,2018-12-03,Category_A,1950-11-11,57,0
4,ID_5,Category_E,71,52.183513,0.067884,98.016506,7.419030,14.083252,28.613473,Category_B,...,7.174542,30.662797,55.812202,0.567308,15.020060,2015-02-16,Category_D,1978-07-26,59,1

Test DataFrame:

,eid,p31,p34,p46_i0,p47_i0,p48_i0,p49_i0,p50_i0,p51_i0,p52,...,p30870_i0,p30880_i0,p30890_i0,p30897_i0,p30900_i0,p130894,p130895,birth_date,age_at_baseline,target
0,ID_1,Category_A,91,36.882165,-0.933434,14.858697,90.655892,75.210007,25.496420,Category_D,...,22.206537,4.974693,10.294670,0.245997,35.427035,2015-06-21,Category_A,1981-06-27,45,0
1,ID_2,Category_C,79,87.938889,0.367980,65.572741,4.056262,59.940714,71.868530,Category_B,...,11.741023,86.485096,53.951537,1.095071,69.859735,2014-07-17,Category_C,1958-10-20,68,1
2,ID_3,Category_D,97,42.568596,0.655031,58.950063,10.058636,37.470965,3.561149,Category_C,...,79.687920,78.899855,76.970329,-0.400309,70.072931,2017-06-10,Category_E,1979-06-17,50,0
3,ID_4,Category_E,32,0.969868,0.764787,91.886462,52.289845,84.364489,89.516763,Category_D,...,36.376610,69.572434,41.385663,-0.426571,92.581323,2009-07-12,Category_C,1970-03-27,67,0
4,ID_5,Category_D,75,84.976662,-1.177674,39.094899,98.296699,88.581374,20.405277,Category_B,...,83.633399,20.916306,77.357650,-1.087116,39.359648,2017-07-25,Category_D,1960-03-16,61,1

Correlation Matrix (Train DataFrame):

,p34,p46_i0,p47_i0,p48_i0,p49_i0,p50_i0,p51_i0,p68_i0,p74_i0,p77_i0,...,p30840_i0,p30850_i0,p30860_i0,p30870_i0,p30880_i0,p30890_i0,p30897_i0,p30900_i0,age_at_baseline,target
p34,1.000000,-0.045756,-0.033549,-0.038945,-0.108722,-0.051122,-0.002352,-0.070266,0.020164,0.065682,...,0.081984,0.029559,-0.066414,-0.012584,0.001679,-0.093668,0.019838,0.012536,-0.047720,-0.048481
p46_i0,-0.045756,1.000000,0.038064,-0.014411,-0.039047,-0.054303,0.020955,-0.008629,0.105334,-0.022249,...,-0.026461,-0.015646,-0.052332,0.098860,-0.030818,-0.045597,0.038436,0.048309,-0.041463,0.004510
p47_i0,-0.033549,0.038064,1.000000,-0.046456,-0.052619,-0.103862,0.058076,-0.009814,-0.010470,-0.010778,...,0.003519,-0.024546,0.008273,-0.057453,-0.036597,0.018857,0.050919,0.017487,-0.037619,0.086967
p48_i0,-0.038945,-0.014411,-0.046456,1.000000,-0.029440,0.013519,-0.052509,-0.019779,0.033068,0.012836,...,-0.021501,0.010103,0.025648,-0.076205,-0.091941,-0.020513,-0.008841,0.035025,-0.059601,0.009693
p49_i0,-0.108722,-0.039047,-0.052619,-0.029440,1.000000,0.006824,0.001396,0.017602,-0.068256,-0.007695,...,-0.019227,-0.046468,0.060788,0.028268,-0.039844,-0.001721,-0.054224,0.018306,-0.070116,-0.011851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
p30890_i0,-0.093668,-0.045597,0.018857,-0.020513,-0.001721,-0.048957,0.035456,0.009825,-0.026554,0.008591,...,0.029019,-0.104416,0.068517,0.002335,0.076488,1.000000,0.050304,-0.023713,0.032205,-0.025664
p30897_i0,0.019838,0.038436,0.050919,-0.008841,-0.054224,0.007969,0.001580,-0.018564,0.077026,-0.022173,...,-0.000425,-0.007566,0.028364,0.059107,-0.007834,0.050304,1.000000,-0.022591,0.043994,0.026475
p30900_i0,0.012536,0.048309,0.017487,0.035025,0.018306,0.004027,0.022472,0.003957,-0.061373,0.053772,...,0.001568,-0.068081,0.009039,0.069269,-0.016855,-0.023713,-0.022591,1.000000,-0.014979,-0.123307
age_at_baseline,-0.047720,-0.041463,-0.037619,-0.059601,-0.070116,-0.050758,0.052390,-0.028041,0.010269,0.001649,...,-0.063092,0.017095,0.071595,0.054296,-0.009824,0.032205,0.043994,-0.014979,1.000000,0.013892
target,-0.048481,0.004510,0.086967,0.009693,-0.011851,-0.025737,0.020169,-0.008629,-0.002104,0.116472,...,0.022163,0.052204,-0.082703,0.021817,0.004140,-0.025664,0.026475,-0.123307,0.013892,1.000000

Correlation Matrix (Test DataFrame):

,p34,p46_i0,p47_i0,p48_i0,p49_i0,p50_i0,p51_i0,p68_i0,p74_i0,p77_i0,...,p30840_i0,p30850_i0,p30860_i0,p30870_i0,p30880_i0,p30890_i0,p30897_i0,p30900_i0,age_at_baseline,target
p34,1.000000,0.067687,-0.058566,-0.077529,-0.004079,0.034059,-0.063863,0.038471,0.076273,0.022733,...,-0.021550,0.007671,-0.041205,0.001226,-0.008976,-0.029108,-0.015686,0.025056,0.040538,-0.001885
p46_i0,0.067687,1.000000,-0.028891,0.005577,-0.036768,-0.027843,0.035292,-0.026451,0.039723,-0.058638,...,0.056235,0.027566,0.071233,-0.047552,-0.013969,-0.018543,-0.004860,-0.071899,-0.003867,0.020431
p47_i0,-0.058566,-0.028891,1.000000,0.036399,-0.036891,0.008918,-0.072130,-0.017813,-0.029892,0.053859,...,0.028843,0.025306,0.010215,-0.027138,-0.004999,0.003374,-0.024792,0.055855,-0.034923,0.116556
p48_i0,-0.077529,0.005577,0.036399,1.000000,0.057165,0.000198,0.080600,-0.009150,-0.035521,-0.115191,...,-0.016704,0.052529,-0.030877,-0.014224,-0.004537,0.006845,0.104708,0.045515,-0.012250,0.009599
p49_i0,-0.004079,-0.036768,-0.036891,0.057165,1.000000,-0.003874,-0.092808,-0.001092,0.059184,-0.033219,...,-0.010152,-0.059020,0.022607,0.084113,-0.002961,-0.047136,-0.010130,-0.044369,-0.020147,-0.037371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
p30890_i0,-0.029108,-0.018543,0.003374,0.006845,-0.047136,-0.006131,0.049013,0.019334,0.023857,-0.071281,...,-0.011066,0.025083,-0.018987,0.037094,-0.046776,1.000000,-0.019300,-0.049244,0.054008,-0.034064
p30897_i0,-0.015686,-0.004860,-0.024792,0.104708,-0.010130,-0.015572,-0.002970,-0.060811,0.040669,0.014607,...,-0.104333,0.013041,-0.082090,0.082256,-0.066883,-0.019300,1.000000,0.050827,-0.040804,0.067648
p30900_i0,0.025056,-0.071899,0.055855,0.045515,-0.044369,-0.010282,0.016923,0.030148,0.034080,0.071911,...,-0.062197,-0.048717,0.011444,0.021514,0.028666,-0.049244,0.050827,1.000000,0.097586,0.009415
age_at_baseline,0.040538,-0.003867,-0.034923,-0.012250,-0.020147,-0.024682,-0.020672,0.036531,-0.027698,0.029900,...,-0.024463,-0.038369,0.076676,-0.007183,-0.032721,0.054008,-0.040804,0.097586,1.000000,-0.035365
target,-0.001885,0.020431,0.116556,0.009599,-0.037371,-0.016955,-0.027143,-0.136030,0.026533,0.091588,...,-0.014746,0.071326,-0.006966,0.097997,-0.047818,-0.034064,0.067648,0.009415,-0.035365,1.000000